### ISSUE TITLE
 Error occurs when using all CellChat interaction types

### ISSUE THREAD

**Issue by wangtanzhang612** [axelalmet/flowsig#2]
Hello, Flowsig is an excellent tool for studying intercellular communication.
However, I encountered some errors while using it.
It seems not to support recognizing all ligand-receptor libraries of Cellchat. fs.pp.construct_flows_from_cellchat can run when only Secreted Signaling is used.

**Comment by axelalmet** [comment]
Hi wangtanzhang612,

Thanks for your interest in FlowSIg! It's not that FlowSig does not explicitly support ligand-receptor interactions due to, e.g., Cell-Cell Contact, but rather, for the analysis in the FlowSig paper, we only considered interactions due to Secreted Signaling. Therefore, for the non-spatial pancreatic islets data (and all others), we only used CellChat to infer Secreted Signaling-based interactions.

While CellChat and other methods allow for other types of ligand-receptor interactions, we felt that secreted interactions are the most reliable to infer from scRNA-seq and thus, would be the most reliable from which we could infer intercellular flows. While there's no guarantee that the ligand-receptor interactions due to Secreted Signaling actually did occur (because the cells are not close enough to interact or due to post-translational modifications), I personally think there's even less of a guarantee that interactions that, for example, require cells to be directly in contact can be reliably inferred from scRNA-seq.

This all being said, you could easily include the other CellChat interaction types in your analysis and FlowSig should run all the same. I tested fs.pp.construct_flows_from_cellchat and other functions on CellChat output that included interactions annotated as either Cell-Cell Contact, ECM-Receptor, or Non-protein Signaling, and it still seems to work.

Best wishes,
Axel.

**Comment by wangtanzhang612** [comment]
Thank you very much for your help. Previously, when I tried to use all four CellChat interaction types simultaneously, I encountered an error related to matching after splitting by "_", but the process went smoothly when I used only the secreted signaling type. I will revisit my data processing steps. Thank you again for your response.

Additionally, could you provide some guidance on visualization, particularly related to multi-group comparisons in COVID-19 research?

**Comment by wangtanzhang612** [comment]
I encountered a new error during testing, two identical scRNA data, one of which was successfully analyzed using a smaller cellchat input. However, the larger CellChat input, fs. tl.apply_biological_flow, encountered the following error: ValueError: The truth value of a Series is ambiguous Use a. empty, a. bool(), a. item(), a. any(), or a. all(). After troubleshooting two adata data, the erroneous data showed the following situation in the output: Node 1: EGFR, Type: inflow
Node 2: CXCL16, Type: outflow
Node 1: IL13, Type: outflow
Node 2: NRG2, Type: outflow
Node 1: ACVR1+BMPR2, Type: inflow
Node 2: PTPRS, Type: PTPRS outflow
PTPRS inflow
Name: Type, dtype: object.
